services:
  express-app:
    build: .
    ports:
      - "3000:8080"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=30  # check for updates every 30 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
