
# replicate command docker run --mount type=bind,source="$(pwd)/local_logs.log",target=/usr/src/app/text.log devopsdockeruh/simple-web-service
#  with Docker compose

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    command: ["server"]  # Run "server" command
    # mount to stream logs locally too
    volumes:
      - type: bind
        source: ./local_logs.log
        target: /usr/src/app/text.log
    # mapping ports, similarly to docker run -p 8000:8080 devopsdockeruh/simple-web-service server
    ports:
      - "8000:8080"
